env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - go mod download

builds:
  - id: x-linux
    ldflags: -s -w -X main.Version={{ .Version }} -X main.BuildDate={{ .Date }} -X main.CommitHash={{ .ShortCommit }}
    binary: jorvit
    main: ./cmd/vitconfig/vitconfig.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
  - id: x-darwin-amd64
    ldflags: -s -w -X main.Version={{ .Version }} -X main.BuildDate={{ .Date }} -X main.CommitHash={{ .ShortCommit }}
    binary: jorvit
    main: ./cmd/vitconfig/vitconfig.go
    env:
      - CGO_ENABLED=0
      # - CC=o64-clang
      # - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: x-windows-amd64
    ldflags: -s -w -X main.Version={{ .Version }} -X main.BuildDate={{ .Date }} -X main.CommitHash={{ .ShortCommit }}
    binary: jorvit
    main: ./cmd/vitconfig/vitconfig.go
    env:
      - CGO_ENABLED=0
      # - CC=x86_64-w64-mingw32-gcc
      # - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - assets/**/*
      - jor_bins/*

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^dev:'
    - 'README'
    - Merge pull request
    - Merge branch

checksum:
  name_template: 'checksums.txt'

#signs:
#  - artifacts: checksum
